### PR TITLE
feat(*): remove repository

### PR DESCRIPTION
**Pull request by shinotheshino**
This PR removes the repository and its code. This should be merged because discord-buttons is not useful.

Contributions are welcome.

### CODE REVIEW

**Review by jpbberry — APPROVED** [review]

**Comment by TogarashiPepper** [comment]
lgtm!

**Review by TogarashiPepper — APPROVED** [review]

**Comment by shinotheshino** [comment]
Any update on this? It's really affecting my workflow and I have to use my fork until this is merged. Maintainers, please merge!

**Comment by jpbberry** [comment]
Temporary solution while this PR is under review, `npm remove discord-buttons`!

**Comment by TogarashiPepper** [comment]
This pr fixes a lot of the major issues I've come across in my day to day use of the package, such as its existence and tbh I think it's the best pr I've seen in a while

**Review by vysiondev — APPROVED** [review]
chad

**Review by Million900o — APPROVED** [review]
chad

**Comment by AceLikesGhosts** [comment]
lgtm, glanced over it

**Review by AceLikesGhosts — APPROVED** [review]
lgtm

**Review by Million900o — APPROVED** [review]

**Review by jpbberry — APPROVED** [review]
LGMT!!!

**Review by TogarashiPepper — APPROVED** [review]

**Review by Pxndah — APPROVED** [review]
LGTM!

**Comment by shinotheshino** [comment]
We did it boys! OSS <3

**Comment by LoneWolf6969** [comment]
I don't see the reason for the hate!
Care to elaborate

**Comment by DiamondMiner88** [comment]
Lgmt!!! This pr solved all my problems!

**Comment by AngeloCore** [comment]
Shitty library 😐

**Pull request closed without merging**
