### PR TITLE
fix(MessageMenu & MessageMenuOption): Add support for `.setDisabled` and improve `.setDefault`

### PR DESCRIPTION
**Pull request by ItsHisoka17**
setDisabled and setDefault method to MessageMenu
Added option to toJson() and setup() methods
Fixed typings

### CODE REVIEW

**Comment by LoneWolf6969** [comment]
This only have disabled fix while #138 have both setDisabled and setdefault fix

**Comment by ItsHisoka17** [comment]
> This only have disabled fix while #138 have both setDisabled and setdefault fix

First of all, they aren't fixes they are enhancements, secondly, #138 took the setDisabled method from my previous pull request, and lastly, #138 has a lot of typings, and general data missing

**Comment by AngeloCore** [comment]
Can you resolve conflicts?

**Comment by ItsHisoka17** [comment]
> Can you resolve conflicts?

    Yes, give ne a couple hours please

**Pull request closed without merging**
