### PR TITLE
Auto style for URL & More

### PR DESCRIPTION
**Pull request by Tolfx**
This is linked to issue #125

`PR` #122 will be invalid if this `PR` will be merged.

### CODE REVIEW

**Comment by Tolfx** [comment]
Might need some testing to be sure it actually works like intended. But for my testing it worked like it should.

**Comment by EhsanFox** [comment]
nah bro!
if we make this happen, everyone will be like, * i have my style on red, why the url button is grey*

**Comment by Tolfx** [comment]
> nah bro!
> if we make this happen, everyone will be like, * i have my style on red, why the url button is grey*

Ok..? I think this will solve more issue due to people not reading the documents. And is more logical if there is only one possible outcome of the style.

**Comment by EhsanFox** [comment]
bro, when they would just ask more nonsense questions!

**Comment by EhsanFox** [comment]
then*

**Comment by alperb** [comment]
I think this should be merged and some error message like #122 should be thrown if dev sets style to a url button.

**Review by DeltaCoderr — APPROVED** [review]
Gotta solve the conflicts.

**Comment by Tolfx** [comment]
> Gotta solve the conflicts.

I've been "resolving" the conflicts already, but the dev branch is broken if you look at it.

**Comment by AngeloCore** [comment]
redo please

**Pull request closed without merging**
