### PR TITLE
Fixed setDefault

### PR DESCRIPTION
**Pull request by Spacey4K**
Default option in message menu option fixed.
This time with the correct files i hope

### CODE REVIEW

**Review by xHyroM — APPROVED** [review]

**Review by AngeloCore — CHANGES_REQUESTED** [review]
Add `.setDefault` option for `MessageMenu`, check #130 for help

**Comment by LoneWolf6969** [comment]
> Add `.setDefault` option for `MessageMenu`, check #130 for help

`.setDisabled()` ?

**Comment by AngeloCore** [comment]
> > Add `.setDefault` option for `MessageMenu`, check #130 for help
> 
> `.setDisabled()` ?

Ah yes, i was wrong

**Comment by ItsHisoka17** [comment]
Added proper typings, option in toJSON() and setup() methods: [setDisabled method (properly) #139](https://github.com/discord-buttons/discord-buttons/pull/139)

**Comment by AngeloCore** [comment]
Sorry but it looks like #144 is better, very sorry

**Pull request closed without merging**
