### PR TITLE
style: fix style issues

### PR DESCRIPTION
**Pull request by shinotheshino**
this fixes a few minor styling issues throughout the code

I added the other ppl who wrote the code since its their code

### CODE REVIEW

**Review by jpbberry — APPROVED** [review]
Great change 👍

**Review by Pxndah — APPROVED** [review]
LGTM :D

**Review by AceLikesGhosts — APPROVED** [review]
LGTM!

**Comment by vysiondev** [comment]
i like trains

**Comment by 1mmunity** [comment]
it ugly looks like binarysus' bot code

**Comment by shinotheshino** [comment]
My apologies for this and my other PR earlier today; I have nothing I can say for my behavior other than that it was immature and without forethought (or really any thought). I apologize for the childish PRs and I will refrain from such behavior. I take full responsibility for any actions of others (comments, etc.), as I was in a voice chat with most of them at the time and should have known better than to encourage such behavior.

**Comment by DeltaCoderr** [comment]
Better think twice, Before doing these things /shrug

**Pull request closed without merging**
